spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: ${HOST_DB:jdbc:postgresql://localhost:5432/tiny_url}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    enabled: true

server:
  port: 8080
base:
  url: http://localhost:${server.port}/
